unique_ids:
  forms:
    Form1: ND4XKQC7K537JK6O7N3IXVDG7JEBUWKJ
    Form1.RowTemplate2: XE33MFZLSD4SR6HWHYMFTURRS5ZWWDVT
    Form1.RowTemplate3: 52HFOVPCMSCRHPLPKP7CKU4KRCYYPVP2
  modules: {}
  server_modules:
    ServerModule1: S5NFBJGXRCOTX6NCXSK6QBN6VQP7HJTX
  assets:
    standard-page.html: XIQ6GRGYUWFAX5MMIPLPO5GJYBTQFJK7
    theme.css: 7NUV6DHDNMFLQDQTQ6JWVYNQCPX3276I
